/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EnrollmentMedicationResponses
 */
export interface EnrollmentMedicationResponses {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMedicationResponses
     */
    Name: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMedicationResponses
     */
    DosageMg?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMedicationResponses
     */
    RefillsPerYear?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentMedicationResponses
     */
    LastTakenDate?: Date | null;
}

