/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EnrollmentAddress
 */
export interface EnrollmentAddress {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentAddress
     */
    AddressLine1: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentAddress
     */
    City: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentAddress
     */
    State: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentAddress
     */
    Zip: string | null;
}

