/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentCondition,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentConditions
 */
export interface EnrollmentConditions {
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BloodDisorderAnemia?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BloodDisorderHemophilia?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BloodDisorderOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointArthritisOsteoarthritis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointBackDisorder?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointBackHerniationOrBulge?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointChiropracticTreatment?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointFracture?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointKneePainInjury?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointRheumatoidArthritis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointShoulderPainInjury?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    BoneJointOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    CancerCancerTumor?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    CancerHodgkinsDisease?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    CancerLymphoma?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    CancerLeukemia?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    CancerOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveCrohnsDisease?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveCeliac?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveColitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveDiverticulitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveGerdAcidReflux?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveUlcerativeColitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    DigestiveOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EarNoseThroatEarInfections?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EarNoseThroatGlaucoma?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EarNoseThroatSinusitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EarNoseThroatTonsillitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EarNoseThroatOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EndocrineAdrenalInsufficiency?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EndocrineDiabetes?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EndocrineGrowthHormoneProblems?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EndocrineHyperthyroidism?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EndocrineHypothyroidism?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    EndocrineOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularAngioplasty?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularBypass?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularChestPain?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularElevatedCholesterol?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularHeartAttack?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularHypertension?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularPeripheralVascularDisease?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    HeartCirculatoryVascularOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ImmuneAidsHiv?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ImmuneLupus?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ImmuneMs?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ImmunePsoriasis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ImmuneOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    KidneyChronicKidneyDisease?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    KidneyCysts?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    KidneyFailure?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    KidneyInfections?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    KidneyPolycysticKidneyDisease?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    KidneyOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    LiverCirrhosis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    LiverHepatitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    LiverFattyLiver?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    LiverOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousAdd?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousAdhd?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousAlcoholDrugAbuseOrDependency?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousAnxiety?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousBipolarDisorder?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousDepression?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousMajorDepressiveDisorder?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MentalNervousOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MuscularMs?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MuscularMuscularDystrophy?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MuscularMyastheniaGravis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MuscularParalysis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    MuscularOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    NeurologicalAlzheimersDisease?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    NeurologicalCerebralPalsy?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    NeurologicalMigrainesHeadaches?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    NeurologicalSeizuresEpilepsy?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    NeurologicalOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    PregnancyMultipleBirths?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    PregnancyNormalPregnancy?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    PregnancyOtherComplications?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    PregnancyPlannedCSection?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ReproductiveAbnormalMenses?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ReproductiveInfertility?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ReproductivePcos?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    ReproductiveOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    RespiratoryAsthma?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    RespiratoryChronicBronchitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    RespiratoryCopd?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    RespiratoryEmphysema?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    RespiratoryOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    TransplantBoneMarrow?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    TransplantHeart?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    TransplantKidney?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    TransplantLiver?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    TransplantLung?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    TransplantOther?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    UrinaryBladderInfectionsInterstitialCystitis?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    UrinaryOveractiveBladder?: EnrollmentCondition;
    /**
     * 
     * @type {EnrollmentCondition}
     * @memberof EnrollmentConditions
     */
    UrinaryOther?: EnrollmentCondition;
}

