/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EnrollmentAdditionalInsuranceInformation
 */
export interface EnrollmentAdditionalInsuranceInformation {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentAdditionalInsuranceInformation
     */
    CarrierName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentAdditionalInsuranceInformation
     */
    HasAdditionalInsurance: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentAdditionalInsuranceInformation
     */
    HasMedicare: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentAdditionalInsuranceInformation
     */
    IdAndGroupNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentAdditionalInsuranceInformation
     */
    WillMedicareRemainActive?: boolean | null;
}

