/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentApplicationSpecificCondition,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentApplicationGeneralCondition
 */
export interface EnrollmentApplicationGeneralCondition {
    /**
     * Application general condition property name used for submit application endpoint payload
     * @type {string}
     * @memberof EnrollmentApplicationGeneralCondition
     */
    Code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentApplicationGeneralCondition
     */
    Description?: string | null;
    /**
     * List of specific conditions that the general condition have in the submit application endpoint payload
     * @type {Array<EnrollmentApplicationSpecificCondition>}
     * @memberof EnrollmentApplicationGeneralCondition
     */
    Conditions?: Array<EnrollmentApplicationSpecificCondition> | null;
}

