/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface EnrollmentApplicationConditions
 */
export interface EnrollmentApplicationConditions {
    /**
     * Blood Disorder - Anemia
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BloodDisorderAnemia?: boolean;
    /**
     * Blood Disorder - Hemophilia
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BloodDisorderHemophilia?: boolean;
    /**
     * Blood Disorder - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BloodDisorderOther?: boolean;
    /**
     * Bone/Joint - Arthritis/Osteoarthritis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointArthritisOsteoarthritis?: boolean;
    /**
     * Bone/Joint - Back Disorder
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointBackDisorder?: boolean;
    /**
     * Bone/Joint - Back Herniation or Bulge
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointBackHerniationOrBulge?: boolean;
    /**
     * Bone/Joint - Chiropractic Treatment
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointChiropracticTreatment?: boolean;
    /**
     * Bone/Joint - Fracture
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointFracture?: boolean;
    /**
     * Bone/Joint - Knee Pain/Injury
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointKneePainInjury?: boolean;
    /**
     * Bone/Joint - Rheumatoid Arthritis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointRheumatoidArthritis?: boolean;
    /**
     * Bone/Joint - Shoulder Pain/Injury
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointShoulderPainInjury?: boolean;
    /**
     * Bone/Joint - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    BoneJointOther?: boolean;
    /**
     * Cancer - Cancer/Tumor
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    CancerCancerTumor?: boolean;
    /**
     * Cancer - Hodgkin's Disease
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    CancerHodgkinsDisease?: boolean;
    /**
     * Cancer - Lymphoma
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    CancerLymphoma?: boolean;
    /**
     * Cancer - Leukemia
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    CancerLeukemia?: boolean;
    /**
     * Cancer - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    CancerOther?: boolean;
    /**
     * Digestive - Crohn's Disease
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveCrohnsDisease?: boolean;
    /**
     * Digestive - Celiac
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveCeliac?: boolean;
    /**
     * Digestive - Colitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveColitis?: boolean;
    /**
     * Digestive - Diverticulitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveDiverticulitis?: boolean;
    /**
     * Digestive - GERD/Acid Reflux
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveGerdAcidReflux?: boolean;
    /**
     * Digestive - Ulcerative colitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveUlcerativeColitis?: boolean;
    /**
     * Digestive - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    DigestiveOther?: boolean;
    /**
     * Ears/Nose/Throat - Ear Infections
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EarNoseThroatEarInfections?: boolean;
    /**
     * Ears/Nose/Throat - Glaucoma
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EarNoseThroatGlaucoma?: boolean;
    /**
     * Ears/Nose/Throat - Sinusitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EarNoseThroatSinusitis?: boolean;
    /**
     * Ears/Nose/Throat - Tonsillitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EarNoseThroatTonsillitis?: boolean;
    /**
     * Ears/Nose/Throat - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EarNoseThroatOther?: boolean;
    /**
     * Endocrine - Adrenal Insufficiency
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EndocrineAdrenalInsufficiency?: boolean;
    /**
     * Endocrine - Diabetes
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EndocrineDiabetes?: boolean;
    /**
     * Endocrine - Growth Hormone problems
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EndocrineGrowthHormoneProblems?: boolean;
    /**
     * Endocrine - Hyperthyroidism
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EndocrineHyperthyroidism?: boolean;
    /**
     * Endocrine - Hypothyroidism
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EndocrineHypothyroidism?: boolean;
    /**
     * Endocrine - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    EndocrineOther?: boolean;
    /**
     * Heart/Circulatory/Vascular - Angioplasty
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularAngioplasty?: boolean;
    /**
     * Heart/Circulatory/Vascular - Bypass
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularBypass?: boolean;
    /**
     * Heart/Circulatory/Vascular - Chest Pain
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularChestPain?: boolean;
    /**
     * Heart/Circulatory/Vascular - Elevated Cholesterol
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularElevatedCholesterol?: boolean;
    /**
     * Heart/Circulatory/Vascular - Heart Attack
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularHeartAttack?: boolean;
    /**
     * Heart/Circulatory/Vascular - Hypertension
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularHypertension?: boolean;
    /**
     * Heart/Circulatory/Vascular - Peripheral Vascular Disease
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularPeripheralVascularDisease?: boolean;
    /**
     * Heart/Circulatory/Vascular - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    HeartCirculatoryVascularOther?: boolean;
    /**
     * Auto Immune/Immune - AIDS/HIV
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ImmuneAidsHiv?: boolean;
    /**
     * Auto Immune/Immune - Lupus
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ImmuneLupus?: boolean;
    /**
     * Auto Immune/Immune - MS
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ImmuneMs?: boolean;
    /**
     * Auto Immune/Immune - Psoriasis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ImmunePsoriasis?: boolean;
    /**
     * Auto Immune/Immune - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ImmuneOther?: boolean;
    /**
     * Kidney - Chronic Kidney Disease
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    KidneyChronicKidneyDisease?: boolean;
    /**
     * Kidney - Kidney Cysts
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    KidneyCysts?: boolean;
    /**
     * Kidney - Kidney Failure
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    KidneyFailure?: boolean;
    /**
     * Kidney - Kidney Infections
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    KidneyInfections?: boolean;
    /**
     * Kidney - Polycystic Kidney Disease
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    KidneyPolycysticKidneyDisease?: boolean;
    /**
     * Kidney - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    KidneyOther?: boolean;
    /**
     * Liver - Cirrhosis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    LiverCirrhosis?: boolean;
    /**
     * Liver - Hepatitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    LiverHepatitis?: boolean;
    /**
     * Liver - Fatty Liver
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    LiverFattyLiver?: boolean;
    /**
     * Liver - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    LiverOther?: boolean;
    /**
     * Mental Nervous - ADD
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousAdd?: boolean;
    /**
     * Mental Nervous - ADHD
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousAdhd?: boolean;
    /**
     * Mental Nervous - Alcohol/Drug Abuse or Dependency
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousAlcoholDrugAbuseOrDependency?: boolean;
    /**
     * Mental Nervous - Anxiety
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousAnxiety?: boolean;
    /**
     * Mental Nervous - Bipolar Disorder
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousBipolarDisorder?: boolean;
    /**
     * Mental Nervous - Depression
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousDepression?: boolean;
    /**
     * Mental Nervous - Major Depressive Disorder
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousMajorDepressiveDisorder?: boolean;
    /**
     * Mental Nervous - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MentalNervousOther?: boolean;
    /**
     * Muscular - MS
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MuscularMs?: boolean;
    /**
     * Muscular - Muscular Dystrophy
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MuscularMuscularDystrophy?: boolean;
    /**
     * Muscular - Myasthenia Gravis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MuscularMyastheniaGravis?: boolean;
    /**
     * Muscular - Paralysis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MuscularParalysis?: boolean;
    /**
     * Muscular - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    MuscularOther?: boolean;
    /**
     * Neurological - Alzheimer's Disease
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    NeurologicalAlzheimersDisease?: boolean;
    /**
     * Neurological - Cerebral Palsy
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    NeurologicalCerebralPalsy?: boolean;
    /**
     * Neurological - Migraines/Headaches
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    NeurologicalMigrainesHeadaches?: boolean;
    /**
     * Neurological - Seizures/Epilepsy
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    NeurologicalSeizuresEpilepsy?: boolean;
    /**
     * Neurological - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    NeurologicalOther?: boolean;
    /**
     * Pregnancy - Multiple Births
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    PregnancyMultipleBirths?: boolean;
    /**
     * Pregnancy - Normal Pregnancy
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    PregnancyNormalPregnancy?: boolean;
    /**
     * Pregnancy - Other Complications
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    PregnancyOtherComplications?: boolean;
    /**
     * Pregnancy - Planned C Section
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    PregnancyPlannedCSection?: boolean;
    /**
     * Reproductive - Abnormal Menses
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ReproductiveAbnormalMenses?: boolean;
    /**
     * Reproductive - Infertility
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ReproductiveInfertility?: boolean;
    /**
     * Reproductive - PCOS
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ReproductivePcos?: boolean;
    /**
     * Reproductive - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    ReproductiveOther?: boolean;
    /**
     * Respiratory - Asthma
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    RespiratoryAsthma?: boolean;
    /**
     * Respiratory - Chronic Bronchitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    RespiratoryChronicBronchitis?: boolean;
    /**
     * Respiratory - COPD
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    RespiratoryCopd?: boolean;
    /**
     * Respiratory - Emphysema
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    RespiratoryEmphysema?: boolean;
    /**
     * Respiratory - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    RespiratoryOther?: boolean;
    /**
     * Transplant - Bone Marrow
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    TransplantBoneMarrow?: boolean;
    /**
     * Transplant - Heart
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    TransplantHeart?: boolean;
    /**
     * Transplant - Kidney
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    TransplantKidney?: boolean;
    /**
     * Transplant - Liver
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    TransplantLiver?: boolean;
    /**
     * Transplant - Lung
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    TransplantLung?: boolean;
    /**
     * Transplant - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    TransplantOther?: boolean;
    /**
     * Urinary - Bladder infections/Interstitial Cystitis
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    UrinaryBladderInfectionsInterstitialCystitis?: boolean;
    /**
     * Urinary - Overactive bladder
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    UrinaryOveractiveBladder?: boolean;
    /**
     * Urinary - Other
     * @type {boolean}
     * @memberof EnrollmentApplicationConditions
     */
    UrinaryOther?: boolean;
}

