/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentApplicationConditionQuestion,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentApplicationSpecificCondition
 */
export interface EnrollmentApplicationSpecificCondition {
    /**
     * Property name for specific conditions in submit application endpoint payload
     * @type {string}
     * @memberof EnrollmentApplicationSpecificCondition
     */
    Code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentApplicationSpecificCondition
     */
    Description?: string | null;
    /**
     * List of questions that a specific condition can have in the submit application endpoint payload
     * @type {Array<EnrollmentApplicationConditionQuestion>}
     * @memberof EnrollmentApplicationSpecificCondition
     */
    Questions?: Array<EnrollmentApplicationConditionQuestion> | null;
    /**
     * List of questions for the prescription that the submit application endpoint payload can have
     * @type {Array<EnrollmentApplicationConditionQuestion>}
     * @memberof EnrollmentApplicationSpecificCondition
     */
    RxQuestions?: Array<EnrollmentApplicationConditionQuestion> | null;
}

