/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentEarningsBasis,
    EnrollmentEmployeeStatus,
    EnrollmentEmploymentStatus,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentEmploymentInformation
 */
export interface EnrollmentEmploymentInformation {
    /**
     * 
     * @type {number}
     * @memberof EnrollmentEmploymentInformation
     */
    AverageHoursPerWeek?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentEmploymentInformation
     */
    CobraEffectiveDate?: Date | null;
    /**
     * 
     * @type {EnrollmentEarningsBasis}
     * @memberof EnrollmentEmploymentInformation
     */
    EarningsBasis?: EnrollmentEarningsBasis;
    /**
     * 
     * @type {EnrollmentEmployeeStatus}
     * @memberof EnrollmentEmploymentInformation
     */
    EmployeeStatus?: EnrollmentEmployeeStatus;
    /**
     * 
     * @type {EnrollmentEmploymentStatus}
     * @memberof EnrollmentEmploymentInformation
     */
    EmploymentStatus?: EnrollmentEmploymentStatus;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentEmploymentInformation
     */
    FullTimeDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentEmploymentInformation
     */
    JobTitle?: string | null;
}

