/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentConditions,
    EnrollmentMaritalStatus,
    Gender,
    Relationship,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentMember
 */
export interface EnrollmentMember {
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentMember
     */
    BirthDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentMember
     */
    ChildNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMember
     */
    FirstName?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof EnrollmentMember
     */
    Gender?: Gender;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMember
     */
    HasAdditionalInsurance?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMember
     */
    HasMedicare?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentMember
     */
    Height?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMember
     */
    IsWaived?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMember
     */
    LastName?: string | null;
    /**
     * 
     * @type {EnrollmentMaritalStatus}
     * @memberof EnrollmentMember
     */
    MaritalStatus?: EnrollmentMaritalStatus;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMember
     */
    MiddleInitial?: string | null;
    /**
     * 
     * @type {Relationship}
     * @memberof EnrollmentMember
     */
    Relationship?: Relationship;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMember
     */
    SocialSecurityNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMember
     */
    UsedTobacco?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentMember
     */
    Weight?: number | null;
    /**
     * 
     * @type {EnrollmentConditions}
     * @memberof EnrollmentMember
     */
    Conditions?: EnrollmentConditions;
}

