/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentEnrollmentType,
    EnrollmentPersonsToBeCovered,
    EnrollmentWaiverReason,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentCoverageInformation
 */
export interface EnrollmentCoverageInformation {
    /**
     * 
     * @type {number}
     * @memberof EnrollmentCoverageInformation
     */
    ChildCount: number | null;
    /**
     * 
     * @type {EnrollmentEnrollmentType}
     * @memberof EnrollmentCoverageInformation
     */
    EnrollmentType: EnrollmentEnrollmentType;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentCoverageInformation
     */
    EnrollmentTypeDetails?: string | null;
    /**
     * 
     * @type {EnrollmentPersonsToBeCovered}
     * @memberof EnrollmentCoverageInformation
     */
    PersonsToBeCovered?: EnrollmentPersonsToBeCovered;
    /**
     * 
     * @type {EnrollmentWaiverReason}
     * @memberof EnrollmentCoverageInformation
     */
    WaiverReason?: EnrollmentWaiverReason;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentCoverageInformation
     */
    WaiverReasonDetails?: string | null;
}

