/* tslint:disable */
/* eslint-disable */
/**
 * Group Markets API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EnrollmentApplicationConditions,
} from './';

/**
 * 
 * @export
 * @interface EnrollmentMedicalHistory
 */
export interface EnrollmentMedicalHistory {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentMedicalHistory
     */
    AdditionalDetails?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMedicalHistory
     */
    AdvisedOfFutureTreatment: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMedicalHistory
     */
    AdvisedOfMedication: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EnrollmentMedicalHistory
     */
    DiagnosedOrTreatedOther: boolean | null;
    /**
     * 
     * @type {EnrollmentApplicationConditions}
     * @memberof EnrollmentMedicalHistory
     */
    Conditions: EnrollmentApplicationConditions;
}

