
export const GlobalStringConstant = [
  {
    fixed_contribution: 'Fixed Contribution',
    eeContribution_fixed_amount: 'Your employer is contributing a fixed amount of $100/month* to distribute across ancillary and supplemental plans for you and your family.',
    ee_term_life_info: '*This amount does not apply to voluntary term life.',
    remaining_er_contribution: 'Remaining Employer Contribution',
    ee_remaining_amount: 'You have the following amount remaining:',
    dolar: '$',
    amount: '100',
    mon: '/mon',
    initial_accident_hospitalization_benefit: 'Initial Accident Hospitalization Benefit',
    accident_hospital_confinement: 'Accident Hospital Confinement Benefit',
    benefit_amout: 'Benefit Amount',
    benefit_period: 'Benefit Period',
    plan_term: 'Plan Term',
    cost_per_employee: 'Cost Per Employee',
    waiting_period: 'Waiting Period',
    portability: 'Portability',
    min_benefit: 'Minimum Benefit',
    benefit_payment: 'Benefit Payment',
    individual_tier: 'INDIVIDUAL TIER',
    hospice_care: 'Hospice Care',
    to_this_plan: 'to this plan',
    lump_sum: 'LUMP SUM',
    weeks: '12 Weeks',
    days: '90 days',
    monthly: 'Monthly',
    sickness: 'SICKNESS',
    accident: 'ACCIDENT',
    after_employer_contribution: 'AFTER EMPLOYER CONTRIBUTION',
    your_employer_contributes: 'Your employer contributes',
    initial_diagnosis_benift: 'Initial Diagnosis Benefit',
    stem_cell_bone_marrow_transplant: 'Stem Cell & Bone Marrow Transplant',
    surgical_anesthesia: 'Surgical/Anesthesia',
    subsequent_critical_illness_event: 'Subsequent Critical Illness Event',
    sudden_cardiac_arrest_benefit: 'Sudden Cardiac Arrest Benefit',
    payable_one_per_lifetime: '*payable once per lifetime',
    emergency_room_benefit: 'Emergency Room Benefit',
    hospital_short_stay: 'Hospital Short Stay',
    payment_max_per_calendar_year: '2 payment maximum per calendar year',
    onceper_calendar_year: 'once per calendar year',
    hospital_confinement_benefit: 'Hospital Confinement Benefit',
    base_on_your_age_income: 'based on your age & Income',
    your_monthly_salary: 'of your Monthly salary',
    daily_benefit_amount: 'DAILY BENEFIT AMOUNT',
    face_value: 'FACE VALUE',
    depends_on_age_income: 'Depends on age & income',
    please_refer_to_plan_detail: 'Please refer to plan details',
    accident_death_benefit: 'Accidental Death Benefit',
    hospital_confinement: 'hospital confinement',
    major_criticalIllness_event: 'Major Critical Illness Event'
  }
]
